apiVersion: v1
kind: PersistentVolume
metadata:
  name: gwm2mqtt-data
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/gwm2mqtt-data
    server: 10.1.1.99
    readOnly: false