apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gwm2mqtt-data
spec:
  storageClassName: ""
  volumeName: gwm2mqtt-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi