secrets:
    base_url: ENC[AES256_GCM,data:uH4f3tGjJZ0XYIghJcbY9VIIFW/5ajo=,iv:gkp5NQoJqatO8f2HNy9wYS8UuIHq5jM5D4FlQ1VKqOA=,tag:s8+fPdnNh+OEQaH1MThlyw==,type:str]
    email: ENC[AES256_GCM,data:U0rpTk6/S6RZwEG7XLpFlnadNUlFCdon,iv:USl33Cc99cmz5Lb7chqel/bsUS5HYozLLBuVewUCzLQ=,tag:rggzLuSZYMsL7DvqBpHb6w==,type:str]
    password: ENC[AES256_GCM,data:pVCAuyTj8FGcVINLfQ==,iv:acYvSYhVa6/f2pnksfcbI/2170L4ZQznO7kw7hPziSE=,tag:hPxnJP0Qisc4EmbV1b6urg==,type:str]
    panel_id: ENC[AES256_GCM,data:Pi3ZA2hxujdwlxSp,iv:nagqHl4rArj2Fir526tsRKyOrQPkCR5xXFZ1vn2JJpg=,tag:dd5W32MxdYf4p70rCS1Zsg==,type:str]
    usercode: ENC[AES256_GCM,data:o6fdOw==,iv:Lkd5/AS28zHH9QWN4UlWRbWXa2KhbTEUl5yUjwh8rKI=,tag:dn8lrA5d1FiDUIK/apJJRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16n5tg0lu2gqwmzcy807dy9jam37v0vash2w6z65cgc5qcyslef4sjd6we3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVGNMVWJqbTFUdk5CMkkr
            Vzc1KzE0VmJ5Vm1iLy9MOUkzbjVMaHBPVUNrCjVCRGtWUkxrZmdkS2krbXZaRHh5
            eGN4Mm1NRCtxQ2VKTGM2NTJDcVVISXMKLS0tIFE1bVZYODdCdTJKcWI5TTYxOEV6
            UEZKY3JHRTErdkpnOXplbXJrZG9LM2sKHs+CNvmLTgAl066+aNNX9OqruPAXyjZx
            fg0qdS6U33hEVpFJXXFFpTClC3UO7ehlwHKUxyHyKa9uoCyZ4h0LBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-08T20:23:17Z"
    mac: ENC[AES256_GCM,data:6YzsVURmReek1ZXVriCCnQrNeKYcOmAc2qFboUekTp0mPwYwov+sHvJQOEtfCBISbn9MP5z3fthgsdYqaOvUeDtykojRV+ifdsgC7DDnTkARiR/zEC31DiccDRFU10LLhiBi76eYbqQDHpAVUH5FxE8OyngZrL70zmAgxIAkBII=,iv:QE7MeOM0KzrVzbJUNoaTPlDWdbt8iKQc2oqwSQHvmRs=,tag:Wa5DJeNmn+qgfgaHygyyjA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
