apiVersion: v1
kind: Secret
metadata:
  name: visonic2mqtt-secret
type: Opaque
data:
  base_url: "{{ .Values.secrets.base_url | toString | b64enc }}"
  email: "{{ .Values.secrets.email | toString | b64enc }}"
  password: "{{ .Values.secrets.password | toString | b64enc }}"
  panel_id: "{{ .Values.secrets.panel_id | toString | b64enc }}"
  usercode: "{{ .Values.secrets.usercode | toString | b64enc }}"