apiVersion: v1
kind: Secret
metadata:
  name: visonic2mqtt-secret
type: Opaque
data:
  base_url: "{{ .Values.secrets.visonic2mqtt.base_url | toString | b64enc }}"
  email: "{{ .Values.secrets.visonic2mqtt.email | toString | b64enc }}"
  password: "{{ .Values.secrets.visonic2mqtt.password | toString | b64enc }}"
  panel_id: "{{ .Values.secrets.visonic2mqtt.panel_id | toString | b64enc }}"
  usercode: "{{ .Values.secrets.visonic2mqtt.usercode | toString | b64enc }}"