apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
type: Opaque
data:
  admin-user: "{{ .Values.secrets.GRAFANA_ADMIN_USERNAME | b64enc }}"
  admin-password: "{{ .Values.secrets.GRAFANA_ADMIN_PASSWORD | b64enc }}"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data
  namespace: argocd
  labels:
    instance: grafana
    app: grafana
    chart: grafana
    release: grafana
spec:
  storageClassName: "nfs-client"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /rpool/home-cluster/grafana-data
    server: 10.1.1.99
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  storageClassName: "nfs-client"
  volumeName: grafana-data
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "{{ .Values.spec.destination.server }}"
  project: default
  source:
    path: ""
    repoURL: "https://grafana.github.io/helm-charts/"
    targetRevision: "8.10.1"
    chart: grafana
    helm:
      parameters:
        - name: ingress.enabled
          value: "true"
        - name: ingress.annotations.kubernetes\.io/ingress\.class
          value: "traefik"
        - name: ingress.annotations.cert-manager\.io/cluster-issuer
          value: "letsencrypt-prod"
        - name: ingress.hosts[0]
          value: "grafana.picturo.us"
        - name: ingress.tls[0].secretName
          value: "grafana-tls"
        - name: ingress.tls[0].hosts[0]
          value: "grafana.picturo.us"
        - name: persistence.enabled
          value: "true"
        - name: persistence.existingClaim
          value: "grafana-data"
        - name: admin.existingSecret
          value: "grafana-admin-credentials"
        - name: admin.userKey
          value: "admin-user"
        - name: admin.passwordKey
          value: "admin-password"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true