apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "{{ .Values.spec.destination.server }}"
  project: default
  source:
    path: ""
    repoURL: "https://otwld.github.io/ollama-helm/"
    targetRevision: "1.4.0"
    chart: ollama
    helm:
      parameters:
        - name: ollama.gpu.enabled
          value: "true"
        - name: ollama.models.pull
          value:
            - "deepseek-r1:8b"
        - name: ollama.models.run
          value:
            - "deepseek-r1:8b"
        - name: ingress.enabled
          value: "true"
        - name: ingress.annotations
          value:
            - "kubernetes.io/ingress.class: traefik"
            - "cert-manager.io/cluster-issuer: letsencrypt-prod"
        - name: ingress.hosts.host
          value: ["deepseek.picturo.us"]
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---