apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "{{ .Values.spec.destination.server }}"
  project: default
  source:
    path: ""
    repoURL: "https://charts.zigbee2mqtt.io/"
    targetRevision: "2.1.1"
    chart: zigbee2mqtt
    helm:
      parameters:
        - name: ingress.enabled
          value: "true"
        - name: ingress.hosts[0].host
          value: "zigbee2mqtt.picturo.us"
        - name: ingress.hosts[0].paths[0].path
          value: "/"
        - name: ingress.hosts[0].paths[0].pathType
          value: "ImplementationSpecific"
        - name: ingress.hosts[0].paths[1].path
          value: "/api"
        - name: ingress.hosts[0].paths[1].pathType
          value: "ImplementationSpecific"
        - name: ingress.tls[0].secretName
          value: "zigbee2mqtt-tls"
        - name: ingress.tls[0].hosts[0]
          value: "zigbee2mqtt.picturo.us"
        - name: statefulset.storage.enabled
          value: "true"
        - name: statefulset.storage.storageClassName
          value: "nfs-client-provisioner"
        - name: statefulset.spec.serviceName
          value: "zigbee2mqtt"
        - name: zigbee2mqtt.advanced.last_seen
          value: "enable"
        - name: zigbee2mqtt.mqtt.server
          value: "mqtt://10.1.3.1:1883"
        - name: zigbee2mqtt.timezone
          value: "Asia/Bangkok"