apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-data
  namespace: argocd
  labels:
    instance: zigbee2mqtt
    app: zigbee2mqtt
    chart: zigbee2mqtt
    release: zigbee2mqtt
spec:
  storageClassName: "nfs-client"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /rpool/home-cluster/zigbee2mqtt
    server: 10.1.1.99
    readOnly: false
---
apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secrets
  namespace: argocd
type: Opaque
data:
  secret.yaml: "{{ .Values.secrets.ZIGBEE2MQTT_SECRETS | b64enc }}"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  destination:
    namespace: argocd
    server: "{{ .Values.spec.destination.server }}"
  project: default
  source:
    path: "charts/zigbee2mqtt"
    repoURL: "https://github.com/bossoq/zigbee2mqtt-chart.git"
    targetRevision: "HEAD"
    # chart: zigbee2mqtt
    helm:
      parameters:
        - name: image.tag
          value: "2.1.1"
        - name: ingress.enabled
          value: "true"
        - name: ingress.hosts[0].host
          value: "zigbee2mqtt.picturo.us"
        - name: ingress.hosts[0].paths[0].path
          value: "/"
        - name: ingress.hosts[0].paths[0].pathType
          value: "ImplementationSpecific"
        - name: ingress.hosts[0].paths[1].path
          value: "/api"
        - name: ingress.hosts[0].paths[1].pathType
          value: "ImplementationSpecific"
        - name: ingress.tls[0].secretName
          value: "zigbee2mqtt-tls"
        - name: ingress.tls[0].hosts[0]
          value: "zigbee2mqtt.picturo.us"
        - name: statefulset.storage.enabled
          value: "true"
        - name: statefulset.storage.existingVolume
          value: "zigbee2mqtt-data"
        - name: statefulset.storage.storageClassName
          value: "nfs-client"
        - name: statefulset.spec.serviceName
          value: "zigbee2mqtt"
        - name: statefulset.volumeMounts[0].mountPath
          value: "/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_087f4397a6c8eb1181a3c4c3de5b81b4-if00-port0"
        - name: statefulset.volumeMounts[0].name
          value: "serial-device"
        - name: statefulset.volumeMounts[1].mountPath
          value: "/app/data"
        - name: statefulset.volumeMounts[1].name
          value: "zigbee2mqtt-secrets"
        - name: statefulset.volumes[0].name
          value: "serial-device"
        - name: statefulset.volumes[0].hostPath.path
          value: "/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_087f4397a6c8eb1181a3c4c3de5b81b4-if00-port0"
        - name: statefulset.volumes[1].name
          value: "zigbee2mqtt-secrets"
        - name: statefulset.volumes[1].secret.secretName
          value: "zigbee2mqtt-secrets"
        - name: zigbee2mqtt.advanced.last_seen
          value: "ISO_8601"
        - name: zigbee2mqtt.advanced.network_key[0]
          value: "166"
        - name: zigbee2mqtt.advanced.network_key[1]
          value: "131"
        - name: zigbee2mqtt.advanced.network_key[2]
          value: "249"
        - name: zigbee2mqtt.advanced.network_key[3]
          value: "27"
        - name: zigbee2mqtt.advanced.network_key[4]
          value: "126"
        - name: zigbee2mqtt.advanced.network_key[5]
          value: "136"
        - name: zigbee2mqtt.advanced.network_key[6]
          value: "170"
        - name: zigbee2mqtt.advanced.network_key[7]
          value: "240"
        - name: zigbee2mqtt.advanced.network_key[8]
          value: "151"
        - name: zigbee2mqtt.advanced.network_key[9]
          value: "89"
        - name: zigbee2mqtt.advanced.network_key[10]
          value: "208"
        - name: zigbee2mqtt.advanced.network_key[11]
          value: "154"
        - name: zigbee2mqtt.advanced.network_key[12]
          value: "25"
        - name: zigbee2mqtt.advanced.network_key[13]
          value: "98"
        - name: zigbee2mqtt.advanced.network_key[14]
          value: "77"
        - name: zigbee2mqtt.advanced.network_key[15]
          value: "122"
        - name: zigbee2mqtt.advanced.pan_id
          value: "45248"
        - name: zigbee2mqtt.advanced.ext_pan_id[0]
          value: "81"
        - name: zigbee2mqtt.advanced.ext_pan_id[1]
          value: "44"
        - name: zigbee2mqtt.advanced.ext_pan_id[2]
          value: "205"
        - name: zigbee2mqtt.advanced.ext_pan_id[3]
          value: "196"
        - name: zigbee2mqtt.advanced.ext_pan_id[4]
          value: "4"
        - name: zigbee2mqtt.advanced.ext_pan_id[5]
          value: "116"
        - name: zigbee2mqtt.advanced.ext_pan_id[6]
          value: "232"
        - name: zigbee2mqtt.advanced.ext_pan_id[7]
          value: "176"
        - name: zigbee2mqtt.advanced.transmit_power
          value: "20"
        - name: zigbee2mqtt.homeassistant.enabled
          value: "true"
        - name: zigbee2mqtt.homeassistant.legacy_action_sensor
          value: "false"
        - name: zigbee2mqtt.homeassistant.status_topic
          value: "homeassistant/status"
        - name: zigbee2mqtt.mqtt.server
          value: "mqtt://mqtt.picturo.us:31883"
        - name: zigbee2mqtt.serial.adapter
          value: "zstack"
        - name: zigbee2mqtt.serial.port
          value: "/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_087f4397a6c8eb1181a3c4c3de5b81b4-if00-port0"
        - name: zigbee2mqtt.timezone
          value: "Asia/Bangkok"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true