apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/homeassistant-config
    server: 10.1.1.99
    readOnly: false