apiVersion: v1
kind: Service
metadata:
  name: homeassistant-http
spec:
  type: ClusterIP
  selector:
    app: homeassistant
  ports:
  - port: 1883
    targetPort: 1883
    name: http
    protocol: TCP