apiVersion: v1
kind: Service
metadata:
  name: homeassistant-http
spec:
  type: ClusterIP
  selector:
    app: homeassistant
  ports:
  - port: 8123
    targetPort: 8123
    name: http
    protocol: TCP