apiVersion: apps/v1
kind: Deployment
metadata:
  name: shairport-sync
  labels:
    app: shairport-sync
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: shairport-sync
  template:
    metadata:
      labels:
        app: shairport-sync
    spec:
      containers:
        - securityContext:
            privileged: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          name: shairport-sync-bedroom
          resources: {}
          hostNetwork: true
          volumeMounts:
            - mountPath: /etc/shairport-sync.conf
              name: shairport-sync-config-bedroom
              subPath: shairport-sync.conf
            - mountPath: /dev/snd
              name: dev-snd
        - securityContext:
            privileged: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          name: shairport-sync-kitchen
          resources: {}
          hostNetwork: true
          volumeMounts:
            - mountPath: /etc/shairport-sync.conf
              name: shairport-sync-config-kitchen
              subPath: shairport-sync.conf
            - mountPath: /dev/snd
              name: dev-snd
      volumes:
        - name: shairport-sync-config-bedroom
          persistentVolumeClaim:
            claimName: shairport-sync-config-bedroom
        - name: shairport-sync-config-kitchen
          persistentVolumeClaim:
            claimName: shairport-sync-config-kitchen
        - name: dev-snd
          hostPath:
            path: /dev/snd
      restartPolicy: Always
