apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-nodeport
spec:
  selector:
    app: qbittorrent
  ports:
    - port: 6680
      targetPort: 6680
      nodePort: 31500
      name: inc-udp
      protocol: UDP
    - port: 6680
      targetPort: 6680
      nodePort: 31500
      name: inc-tcp
      protocol: TCP
  type: NodePort