apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-frigate
  labels:
    app: home-frigate
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: home-frigate
  template:
    metadata:
      labels:
        app: home-frigate
    spec:
      runtimeClassName: nvidia
      containers:
        - env:
          - name: TZ
            value: Asia/Bangkok
          - name: FRIGATE_RTSP_PASSWORD
            valueFrom:
              secretKeyRef:
                key: frigate-rtsp-password
                name: home-frigate-secret
          - name: YOLO_MODELS
            value: yolov7-tiny-416
          - name: USE_FP16
            value: "true"
          securityContext:
            privileged: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          name: frigate
          resources:
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /config
              name: home-frigate-config
            - mountPath: /media/frigate
              name: home-frigate-data
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /tmp/cache
              name: cache
          livenessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
      volumes:
        - name: home-frigate-config
          persistentVolumeClaim:
            claimName: home-frigate-config
        - name: home-frigate-data
          persistentVolumeClaim:
            claimName: home-frigate-data
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: cache
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
      restartPolicy: Always
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule