apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-frigate-config
spec:
  storageClassName: ""
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/home-frigate/config
    server: 10.1.1.99
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-frigate-data
spec:
  storageClassName: ""
  capacity:
    storage: 4.5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data-pool/IPCAM
    server: 10.1.1.99
    readOnly: false