apiVersion: v1
kind: Secret
metadata:
  name: home-frigate-secret
type: Opaque
data:
  frigate-rtsp-password: "{{ .Values.secrets.frigate_rtsp_password | toString | b64enc }}"
  plus-api-key: "{{ .Values.secrets.plus_api_key | toString | b64enc }}"