apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-data
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/mosquitto-data
    server: 10.1.1.99
    readOnly: false